import Config

# Configure your database
# CANOPY_DB lets the browser end-to-end suite (e2e/) run on its own database.
config :canopy, Canopy.Repo,
  database: System.get_env("CANOPY_DB") || Path.expand("../canopy_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Canopy listens on loopback unless CANOPY_BIND says otherwise. There is no
# login, so `CANOPY_BIND=0.0.0.0 mix phx.server` hands the whole workspace to
# anyone on the network: use it on a network you trust, for a session.
bind_ip =
  case System.get_env("CANOPY_BIND") do
    nil ->
      {127, 0, 0, 1}

    value ->
      case :inet.parse_address(String.to_charlist(value)) do
        {:ok, ip} -> ip
        {:error, _} -> raise "CANOPY_BIND must be an IP address such as 0.0.0.0, got: #{value}"
      end
  end

config :canopy, CanopyWeb.Endpoint,
  http: [ip: bind_ip, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "j76sTC7ZN9Vmv8QFU/0HxblJhLc8mbDV2X6nu18aIvNrrQsi18KcsDb8sFk/oTwl",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:canopy, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:canopy, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :canopy, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
